homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: 118
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret api_password

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

logger: !include logger.yaml
#logger:

mqtt:
  broker: 10.10.10.101
  port: 1883
  client_id: home-assistant-1
  #keepalive: 60

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'

switch: !include switch.yaml

sensor: !include_dir_list sensor

binary_sensor: !include_dir_list binary_sensor

#device_tracker: !include device_tracker.yaml
device_tracker: !include_dir_list device_tracker

group: !include group.yaml

shell_command: !include shell_command.yaml

automation: !include_dir_merge_list automation

climate: !include_dir_list climate

notify: !include notification.yaml

media_player: !include_dir_list media_player

light: !include_dir_list light

lock: !include_dir_list lock

#input_slider: !include input-slider.yaml
input_number: !include input-slider.yaml
#input_slider: !include_dir_list input_sliders

input_select: !include input-select.yaml
#input_select: !include_dir_named input_selects

#input_boolean: !include input-booleans.yaml
input_boolean: !include_dir_merge_named input_boolean

#script: !include scripts.yaml
script: !include_dir_merge_named script

alexa: !include alexa.yaml

scene: !include_dir_list scene

cover: !include_dir_list cover

emulated_hue:
  #type: alexa
  host_ip: 10.10.10.101
  #listen_port: 8300
  listen_port: 80
  #off_maps_to_on_domains:
    #- script
    #- scene
  expose_by_default: false
  #exposed_domains:
    #- light
    #- scene
    #- switch
    #- group
    #- media_player
    #- script
    #- input_boolean
google_assistant:
  project_id: hass-18326
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  exposed_domains:
    - switch
    - light
    - group
    - cover

ifttt:
  key: !secret ifttt_key

recorder:
  purge_interval: 2
  purge_keep_days: 7
  db_url: !secret db_url
