#####################################################################################
###  Brighten cabinet lights in the morning and dim them at night
###
#####################################################################################
- alias: 'Cabinet lights - Dim at 11pm'
  trigger:
    platform: time
    at: '23:00'
  action:
    - service: mqtt.publish
      data_template:
        topic: "smartthings/Cabinet Lights/level"
        payload: '40'
    - service: light.turn_on
      data:
        entity_id: light.cabinet_lights

- alias: 'Cabinet lights - Brighten at 5am'
  trigger:
    platform: time
    at: '05:00'
  action:
    - service: mqtt.publish
      data_template:
        topic: "smartthings/Cabinet Lights/level"
        payload: '99'
    - service: light.turn_on
      data:
        entity_id: light.cabinet_lights
