########################################
### Notify me via slack if a device goes offline for 5 minutes
########################################
- alias: Notify if a device goes offline for 5 minutes
  trigger:
    platform: state
    entity_id:
      - sensor.garagedooresp
      - sensor.jackcam
      - sensor.ryancam
      - sensor.livingroomcam
      - sensor.bonusroomcam
    state: 'Offline'
    for: 00:05:00
  action:
    service: notify.slack_notifications
    data_template:
      #message: "Garage Door ESP module is offline"
      message: "{{ trigger.entity_id.split('.')[1]|replace('_', ' ') }} is now {{ trigger.to_state.state }}"
