- alias: BlueIris - Disable jack and ryan cameras at 7:30pm and 10:30pm if we are home
  trigger:
    - platform: time
      at: '19:30'
    - platform: time
      at: '22:00'
  condition:
    condition: state
    entity_id: group.presence
    state: 'home'
  action:
    service: shell_command.set_cams_disabled
