#####################################################################################
###  automation to turn on/off the front outside lights
###
#####################################################################################

- alias: 'Outside Lights - Turn on front lights at sunset'
  trigger:
    platform: sun
    event: sunset
  #condition:
    #condition: state
    #entity_id: group.outside_lights
    #state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: 
      #- group.outside_lights
      #- switch.outdoor_switch
      #- switch.christmas_lights
      - light.driveway_lights
      - light.front_porch_lights


- alias: 'Outside Lights - Turn off at 10:30pm'
  trigger:
    platform: time
    at: '22:30'
  #condition:
    #condition: state
    #entity_id: group.outside_lights
    #state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: 
      #- group.outside_lights
      #- switch.outdoor_switch
      - light.driveway_lights
      - light.front_porch_lights
