#####################################################################################
###  automation to do stuff when we get home or leave
###
#####################################################################################

- alias: Do stuff when we get home
  trigger:
    - platform: state
      entity_id: group.presence
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'home'

    - service: mqtt.publish
      data_template:
        topic: "smartthings/Cabinet Lights/level"
        payload: '{{ 99 if now().strftime("%H")|int < 23 else 40 }}'
    - service: light.turn_on
      data:
        entity_id: light.cabinet_light

- alias: Do stuff when we leave
  trigger:
    - platform: state
      entity_id: group.presence
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'away'

    #- service: homeassistant.turn_on
      #data:
        #entity_id:
          #- script.goodbye

- alias: Turn off stuff when we're gone for 10 minutes
  trigger:
    - platform: state
      entity_id: group.presence
      state: 'not_home'
      for: 00:10:00
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.living_room
          - light.breakfast_area_lights
          - light.kitchen_lights
          - light.upstairs_hall_lamp
          - light.upstairs_hall_lights
          - light.bonus_room_lights
          - light.master_bedroom_lights
          - group.all_switches
          - media_player.living_room_tv
          - light.mudroom_lights
