######################################################################
##  What did she say? REPEAT THE LAST MESSAGE.
######################################################################
alias: 'tts_repeat'
trigger:
  platform: state
  entity_id: input_boolean.last_message
  state: 'on'
  from: 'off'
action:
  service: script.voice_notify
  data_template:
    where: living_room
    what: "{{states('sensor.notifications_lastmsg')}}"
