alias: 'Turn off outside lights at 10pm'
trigger:
  platform: time
  after: '22:00'
condition:
  condition: state
  entity_id: group.outside_lights
  state: 'on'
action:
  service: light.turn_off
  entity_id: group.outside_lights